### ISSUE TITLE
newest version of R and bioconductor not compatible with cerebroApp

### ISSUE THREAD

**Issue by lakikowolfe** [romanhaa/cerebroApp#31]
I recently tried to begin using cerebroApp to visualize single cell data and am having trouble installing and using the package. I am using Bioconductor version 3.13 (BiocManager 1.30.16) and R 4.1.0. 

When I run `BioCManager::install("cerebroApp")` I get this error:
```
In .inet_warning(msg) :
  package ‘cerebroApp’ is not available for Bioconductor version '3.13'
```
Which version of Bioconductor and R do you recommend for running this application?

**Comment by lakikowolfe** [comment]
Based on the `sessionInfo()` shown [here](https://romanhaa.github.io/cerebroApp/articles/export_a_data_set_in_SCE_format.html#session-info-1) I reverted R to 4.0.3 and Bioconductor to 3.12. I am still getting the same error as above. 

I tried using `install.packages` as shown [here](https://romanhaa.github.io/cerebroApp/articles/host_cerebro_on_shinyapps.html) and got the following error: `package ‘cerebroApp’ is not available for this version of R`

**Comment by romanhaa** [comment]
Hi Lauren! `cerebroApp` has never been added to the Bioconductor repositories, so you'll have to add the `romanhaa/` prefix to the package name to install it from GitHub directly. It's just recommended to use the Bioconductor installer to get all the dependencies. So the command to install `cerebroApp` would be:

```r
BiocManager::install("romanhaa/cerebroApp")
```

Note: I cannot test this with the newest versions of R and Bioconductor so no guarantee that it'll work, but it should at the very least bring you one step forward.

**Comment by lakikowolfe** [comment]
Hi! I appreciate your quick response and will give this a try. I definitely would recommend you update your articles to reflect this because it is not clear.
