### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by jkvist** [romanhaa/cerebroApp#9]
The latest version fails to install, with the following error:

Error in parse(outFile) : 
  /tmp/RtmpTkSaQo/R.INSTALL675b69122492/cerebroApp/R/calculatePercentGenes.R:41:5: unexpected '{'
40:     if ( ( is.null(object@raw.data) )

The latest change calculatePercentGenes.R is missing a comma
if ( ( is.null(object@raw.data) )
if ( ( is.null(object@raw.data) )**)**

**Comment by romanhaa** [comment]
Hi @jkvist,

I apologize for the error, that shouldn't have happened. It should be fixed in the current master branch. Please let me know if you continue having issues installing/using cerebroApp.

Cheers,
Roman

**Comment by jkvist** [comment]
Hi Roman,

Install works now. Thanks.

Regards,
Jouni
